#!/usr/bin/env bash
set -euo pipefail

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
BUILDER="$ROOT/skills/governance/skill-catalog-router/scripts/build_index.py"
FIXTURE=$(mktemp -d)
trap 'rm -rf -- "$FIXTURE"' EXIT

REPO="$FIXTURE/repo"
OUTSIDE="$FIXTURE/outside"
mkdir -p \
  "$REPO/skills/governance/skill-catalog-router" \
  "$REPO/global-runtime/accelerate" \
  "$REPO/safe/real-parent" \
  "$OUTSIDE"
cp "$ROOT/skills/governance/skill-catalog-router/SKILL.md" \
  "$REPO/skills/governance/skill-catalog-router/SKILL.md"
cp "$ROOT/global-runtime/accelerate/SKILL.md" \
  "$REPO/global-runtime/accelerate/SKILL.md"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

expect_fail() {
  local label=$1
  shift
  if "$@" >"$FIXTURE/$label.stdout" 2>"$FIXTURE/$label.stderr"; then
    fail "$label unexpectedly succeeded"
  fi
}

# Normal writes remain checkable and byte-idempotent.
INDEX="$REPO/safe/index.tsv"
python3 "$BUILDER" --repo-root "$REPO" --index "$INDEX" --write
FIRST_HASH=$(sha256sum "$INDEX" | awk '{print $1}')
python3 "$BUILDER" --repo-root "$REPO" --index "$INDEX" --check
python3 "$BUILDER" --repo-root "$REPO" --index "$INDEX" --write
SECOND_HASH=$(sha256sum "$INDEX" | awk '{print $1}')
[[ "$FIRST_HASH" == "$SECOND_HASH" ]] || fail "normal write is not idempotent"

# An index symlink must never redirect generated bytes outside the repository.
OUTSIDE_INDEX="$OUTSIDE/index.tsv"
cp "$ROOT/global-runtime/accelerate/SKILL.md" "$OUTSIDE_INDEX"
OUTSIDE_HASH=$(sha256sum "$OUTSIDE_INDEX" | awk '{print $1}')
ln -s "$OUTSIDE_INDEX" "$REPO/safe/index-link.tsv"
expect_fail destination-symlink \
  python3 "$BUILDER" --repo-root "$REPO" \
  --index "$REPO/safe/index-link.tsv" --write
expect_fail check-destination-symlink \
  python3 "$BUILDER" --repo-root "$REPO" \
  --index "$REPO/safe/index-link.tsv" --check
[[ "$(sha256sum "$OUTSIDE_INDEX" | awk '{print $1}')" == "$OUTSIDE_HASH" ]] || \
  fail "destination symlink modified its external target"

# A symlink in the destination parent chain is rejected even when it resolves
# back inside the repository; path identity must not depend on indirection.
ln -s "$REPO/safe/real-parent" "$REPO/safe/linked-parent"
expect_fail parent-symlink \
  python3 "$BUILDER" --repo-root "$REPO" \
  --index "$REPO/safe/linked-parent/index.tsv" --write
[[ ! -e "$REPO/safe/real-parent/index.tsv" ]] || \
  fail "write traversed a symlinked parent"

mkdir "$OUTSIDE/parent-target"
ln -s "$OUTSIDE/parent-target" "$REPO/safe/outside-parent"
expect_fail outside-parent-symlink \
  python3 "$BUILDER" --repo-root "$REPO" \
  --index "$REPO/safe/outside-parent/index.tsv" --write
[[ ! -e "$OUTSIDE/parent-target/index.tsv" ]] || \
  fail "write escaped through a symlinked parent"

# Explicit lexical or resolved escapes, dangling links, and non-regular
# destinations are all fail-closed before any write.
expect_fail outside-destination \
  python3 "$BUILDER" --repo-root "$REPO" \
  --index "$OUTSIDE/direct-index.tsv" --write
[[ ! -e "$OUTSIDE/direct-index.tsv" ]] || fail "outside index was created"

ln -s "$OUTSIDE/missing-index.tsv" "$REPO/safe/dangling-index.tsv"
expect_fail dangling-symlink \
  python3 "$BUILDER" --repo-root "$REPO" \
  --index "$REPO/safe/dangling-index.tsv" --write
[[ ! -e "$OUTSIDE/missing-index.tsv" ]] || fail "dangling link target was created"

mkdir "$REPO/safe/directory-index.tsv"
expect_fail non-regular-destination \
  python3 "$BUILDER" --repo-root "$REPO" \
  --index "$REPO/safe/directory-index.tsv" --write

# Force os.replace to fail after the temporary file is complete. The original
# destination must remain byte-identical and the sibling temporary file must be
# removed by the builder's cleanup path.
BUILDER="$BUILDER" REPO="$REPO" INDEX="$INDEX" python3 - <<'PY'
import hashlib
import importlib.util
import os
import sys
from pathlib import Path

builder_path = Path(os.environ["BUILDER"])
repo = Path(os.environ["REPO"])
index = Path(os.environ["INDEX"])
original = index.read_bytes()
original_digest = hashlib.sha256(original).hexdigest()
sys.dont_write_bytecode = True

spec = importlib.util.spec_from_file_location("router_build_index", builder_path)
if spec is None or spec.loader is None:
    raise SystemExit("unable to import builder")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

observed_temp: Path | None = None

def reject_replace(source, destination):
    global observed_temp
    source_path = Path(source)
    destination_path = Path(destination)
    observed_temp = source_path
    assert source_path.parent == destination_path.parent == index.parent
    assert source_path.is_file() and not source_path.is_symlink()
    assert destination_path.read_bytes() == original
    raise OSError("forced replace failure")

module.os.replace = reject_replace
sys.argv = [
    str(builder_path),
    "--repo-root", str(repo),
    "--index", str(index),
    "--write",
]
try:
    module.main()
except SystemExit as error:
    if error.code == 0:
        raise AssertionError("forced os.replace failure unexpectedly succeeded")
else:
    raise AssertionError("forced os.replace failure unexpectedly succeeded")

assert observed_temp is not None, "builder did not use os.replace"
assert not observed_temp.exists(), "temporary index survived failed replace"
assert hashlib.sha256(index.read_bytes()).hexdigest() == original_digest
PY

echo "skill catalog router index atomicity passed"
